#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔎 Running TypeScript type checking..."
npm run typecheck || exit 1

echo "🎨 Running ESLint..."
npm run lint || exit 1

echo "✨ Running formatting..."
npm run format || exit 1

echo "🧪 Running tests..."
npm run test || exit 1

echo "🧪 Running tests..."
npm run start || exit 1

echo "✅ All checks passed!" 